version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Build started on `date`
      - pip3 install --target . boto3 mako testresources
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
